Implement PDP client using Plain Old Java Objects.
build-security/opa-java-client pull request #1
Opened 2021-03-03 06:40 UTC by yashtewari

2021-03-04 15:33 UTC, shahar-davidson requested changes
1. Need to add JavaDoc to all the public classes and their public methods.
2. Need to update the README

2021-03-04 15:33 UTC, shahar-davidson commented on src/main/java/security/build/pdp/client/PdpClient.java
> +            } catch (NumberFormatException exception) {
Please add a comment that if the port cannot be parsed then we're defaulting to the default port

2021-03-04 15:33 UTC, shahar-davidson commented on src/main/java/security/build/pdp/client/PdpClient.java
> +            } catch (NumberFormatException exception) {
Same here (and in the rest of the below NumberFormatException) - add a comment that upon failure we are defaulting to the default value.

2021-03-04 15:33 UTC, shahar-davidson commented on src/main/java/security/build/pdp/client/PdpClient.java
> +    public JsonNode getJsonResponse(Map<String, Object> input) throws Throwable {
Please have some unit-test cover this function.

2021-03-04 15:33 UTC, shahar-davidson commented on src/main/java/security/build/pdp/client/PdpClient.java
> +    public Map<String, Object> getMappedResponse(Map<String, Object> input) throws Throwable {
Please have some unit-test cover this function.

2021-03-04 15:33 UTC, shahar-davidson commented on src/main/java/security/build/pdp/client/PdpClient.java
> +    public Map<String, Object> getMappedResponse(PdpRequest request) throws Throwable {
Please have some unit-test cover this function.

2021-03-04 15:33 UTC, shahar-davidson commented on src/main/java/security/build/pdp/client/PdpClient.java
> +    public String getPdpEndpoint() throws Throwable {
I suggest to add some inline comments here, for the maintaining developers, to explain why this logic below is done, and the best efforts that are done here.

2021-03-09 08:35 UTC, shahar-davidson commented on README.md
> +`readTimeoutMilliseconds` | P`DP_READ_TIMEOUT_MILLISECONDS` | Duration to wait on the response stream, in milliseconds
note the "P" before the quote

2021-03-09 08:39 UTC, shahar-davidson requested changes

2021-03-09 08:39 UTC, shahar-davidson commented on README.md
> +--- | --- | ---
in general, it would be nice (but not a must) to add an 'example' column to show the user how the parameter should be supplied.
Also, add a column of default values so that developers will know what's the default value.

2021-03-09 08:58 UTC, yashtewari commented on README.md
> +--- | --- | ---
I was going to, but I don't think our defaults are good right now, and changing them would break compatibility with the other clients. But it makes sense to add them now and change during the standardization process.

2021-03-09 09:11 UTC, yashtewari commented on README.md
> +--- | --- | ---
As for the example, we're showing it along with how `Builder` works under **Usage**

2021-03-09 10:53 UTC, shahar-davidson approved these changes

2021-03-09 10:54 UTC, merged